/// Constants for BBS GOLD Mobile Application.
abstract class AppConstants {
  // Brand details
  static const String appName = 'BBS GOLD';
  static const String sinceTag = 'SINCE 1985';
  static const String tagline = 'Trusted Jewellery Wholesale Partner';
  static const String welcomeTitle = 'Welcome to BBS GOLD';
  static const String welcomeSubtitle =
      'Premier B2B platform connecting verified jewellery retailers with trusted gold wholesalers & manufacturers.';

  // Assets
  static const String logoAsset = 'assets/BSSGoldLogo.png';
  static const String logoAssets = 'assets/BSSGoldLogo1.png';

  // Feature Card Content
  static const String feature1Title = 'Verified Retailers';
  static const String feature1Subtitle =
      'Exclusive B2B access reserved for verified jewellery shop owners & wholesalers.';

  static const String feature2Title = 'Premium Gold Collection';
  static const String feature2Subtitle =
      'Direct access to hallmark-certified 22K & 18K gold jewellery inventory.';

  static const String feature3Title = 'Fast Wholesale Ordering';
  static const String feature3Subtitle =
      'Seamless digital bulk order placement, approval workflows & live dispatch tracking.';

  // Legal & Buttons
  static const String ctaContinue = 'Continue';
  static const String termsText = 'By continuing, you agree to our ';
  static const String termsLink = 'Terms of Service';
  static const String andText = ' & ';
  static const String privacyLink = 'Privacy Policy';

  // Login Screen Strings
  static const String loginTitle = 'Sign In to Portal';
  static const String loginSubtitle =
      'Enter your credentials to access wholesale pricing and live inventory.';
  static const String emailOrUserIdLabel = 'Email or User ID';
  static const String emailOrUserIdHint = 'Enter your email or User ID';
  static const String passwordLabel = 'Password';
  static const String passwordHint = 'Enter your password';
  static const String rememberMe = 'Remember Me';
  static const String forgotPassword = 'Forgot Password?';
  static const String loginButton = 'Sign In';
  static const String dontHaveAccount = "Don't have an account?";
  static const String registerNow = 'Register Now';
  static const String developedBy = 'Developed by ';
  static const String developerName = 'Shris Innovations';

  // Registration Screen Strings
  static const String registerTitle = 'Create Retailer Account';
  static const String registerSubtitle =
      'Send your registration request for approval.';
  static const String fullNameLabel = 'Full Name';
  static const String fullNameHint = 'Enter your full name';
  static const String mobileLabel = 'Mobile Number';
  static const String mobileHint = '10-digit mobile number';
  static const String emailLabel = 'Email Address';
  static const String emailHint = 'yourname@gmail.com';
  static const String userIdLabel = 'User ID';
  static const String userIdPlaceholder = 'Will be generated by server';
  static const String shopNameLabel = 'Jewellery Shop Name';
  static const String shopNameHint = 'Enter registered shop name';
  static const String addressLabel = 'Shop Address';
  static const String addressHint = 'Complete registered shop address';
  static const String regPasswordLabel = 'Account Password';
  static const String regPasswordHint = 'Create strong password';
  static const String sendRequestButton = 'Send Registration Request';

  // Verification Dialog
  static const String verificationDialogTitle = 'Request Under Review';
  static const String verificationDialogMessage =
      'Account verification is in process.\n\nPlease connect with the Owner, Dealer or BBS Team.';
  static const String verificationDialogBtn = 'OK';
}
